import type { AdminPermissions, AdminRole } from "@/types/auth";

export const DEFAULT_ROLE_PERMISSIONS: Record<AdminRole, AdminPermissions> = {
  superadmin: {
    canViewDashboard: true,
    canManageLeads: true,
    canEditLeads: true,
    canConvertLeads: true,
    canManageClients: true,
    canEditClients: true,
    canManageBlog: true,
    canUploadMedia: true,
    canManageUsers: true,
    canViewStats: true,
    canManageSettings: true,
  },
  admin: {
    canViewDashboard: true,
    canManageLeads: true,
    canEditLeads: true,
    canConvertLeads: true,
    canManageClients: true,
    canEditClients: true,
    canManageBlog: true,
    canUploadMedia: true,
    canManageUsers: true,
    canViewStats: true,
    canManageSettings: false,
  },
  editor: {
    canViewDashboard: true,
    canManageLeads: true,
    canEditLeads: true,
    canConvertLeads: false,
    canManageClients: true,
    canEditClients: true,
    canManageBlog: true,
    canUploadMedia: true,
    canManageUsers: false,
    canViewStats: true,
    canManageSettings: false,
  },
  viewer: {
    canViewDashboard: true,
    canManageLeads: false,
    canEditLeads: false,
    canConvertLeads: false,
    canManageClients: false,
    canEditClients: false,
    canManageBlog: false,
    canUploadMedia: false,
    canManageUsers: false,
    canViewStats: true,
    canManageSettings: false,
  },
};
